# Chapter: Best Practices

# Topic: Feature Engineering (one-hot encoding)

In [2]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

x = np.array([['type A'],
              ['type C'],
              ['type B'],
              ['type C']])
ohe = OneHotEncoder(sparse=False) # sparse=False returns array
X_encoded = ohe.fit_transform(x) # x in numerical form

print(X_encoded)
print(ohe.categories_)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
[array(['type A', 'type B', 'type C'], dtype='<U6')]
